# Generated by Django 6.0.7 on 2026-07-31 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='upated_at',
            new_name='updated_at',
        ),
    ]
